### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress-v1#85]
A number of users are moving to PHP8.0 as their default server. Just like we did with ClassicPress/ClassicPress#494 We can make a move on this slowly.

**ISSUE UPDATED**
Issues:
https://github.com/ClassicPress/ClassicPress/issues?q=is%3Aopen+is%3Aissue+label%3A%22PHP+8%22

PRs:
https://github.com/ClassicPress/ClassicPress/pulls?q=is%3Apr+label%3A%22PHP+8%22

## TODO
- [x] Set up our own testing and build process for PHP8 ref: https://core.trac.wordpress.org/ticket/50902
- [x] Cherry Pick from [WordPress PHP 8 on trac](https://core.trac.wordpress.org/query?keywords=~php8) need testing and reviewing if they apply to ClassicPress.
- [x] Follow the WP baseline for some backports https://core.trac.wordpress.org/ticket/50913
- [x] https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/
- [x] https://github.com/ClassicPress/ClassicPress-v1/issues/26
